version: '3'
services:
  backend:
    build:
      context: ./back/mydisk  # Путь к папке с проектом Django
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./front/yandex-disk-viewer  # Путь к папке с проектом React
    container_name: react-frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
